version: 2.1

jobs:
  build_and_test: # this can be any name you choose
    docker:
      - image: cimg/node:20.6.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app
      - run:
          name: Danger
          command: yarn danger ci

workflows:
  build_test_deploy: # this can be any name you choose
    jobs:
      - build_and_test:
        filters:
          branches:
            only: main # only deploy when on main
